# Generated by Django 2.1.7 on 2019-03-28 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('desc', models.CharField(db_column='Description', max_length=500)),
                ('cat', models.CharField(db_column='Category', max_length=50)),
                ('price', models.IntegerField(db_column='Price')),
                ('image_url', models.CharField(db_column='Image Link', max_length=200)),
                ('seller_url', models.CharField(db_column='Seller Link', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('user', models.OneToOneField(db_column='User', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rec1', models.IntegerField(db_column='Recommendation 1')),
                ('rec2', models.IntegerField(db_column='Recommendation 2')),
                ('rec3', models.IntegerField(db_column='Recommendation 3')),
                ('rec4', models.IntegerField(db_column='Recommendation 4')),
                ('rec5', models.IntegerField(db_column='Recommendation 5')),
            ],
        ),
    ]
