# Generated by Django 2.1.7 on 2019-05-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name_plural': 'Recommendations'},
        ),
    ]
