# Generated by Django 2.1.7 on 2019-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='timestamp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='txnid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
        migrations.AlterModelTable(
            name='txnhistory',
            table='TxnHistory',
        ),
    ]
