# Generated by Django 2.1.7 on 2019-05-16 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txnhistory',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='recommender.Products'),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='status',
            field=models.BooleanField(db_column='status'),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='timestamp',
            field=models.IntegerField(db_column='timestamp'),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
