# Generated by Django 2.1.7 on 2019-05-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20190515_2321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
