# Generated by Django 2.1.7 on 2019-05-16 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20190516_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='recommender.Products'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='rank',
            field=models.IntegerField(db_column='rank'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='score',
            field=models.FloatField(db_column='score'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Products'),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='timestamp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='txnhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
