# Generated by Django 2.1.7 on 2019-05-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20190506_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='rec6',
            field=models.IntegerField(db_column='Recommendation 6', default='1'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='rec7',
            field=models.IntegerField(db_column='Recommendation 7', default='2'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='rec8',
            field=models.IntegerField(db_column='Recommendation 8', default='3'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='rec9',
            field=models.IntegerField(db_column='Recommendation 9', default='4'),
        ),
    ]
