# Generated by Django 2.1.7 on 2019-05-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20190515_2325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
        migrations.AlterModelTable(
            name='txnhistory',
            table=None,
        ),
    ]
