# Generated by Django 2.1.7 on 2019-05-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20190515_2327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
