# Generated by Django 2.1.7 on 2019-05-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20190515_2328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='txnhistory',
            table='TxnHistory',
        ),
    ]
